services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    image: ghcr.io/sygeman/dream/mono-api
    ports:
      - '3333:3333'
    environment:
      - PRISMA_MONO_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      - REDIS_URL=redis://redis:6379
      - TWITCH_ID=${TWITCH_ID}
      - TWITCH_SECRET=${TWITCH_SECRET}
      - YOUTUBE_KEY=${YOUTUBE_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - NEXT_PUBLIC_MONO_API=${NEXT_PUBLIC_MONO_API}

  client:
    image: ghcr.io/sygeman/dream/mono-client
    environment:
      - PRISMA_MONO_URL=${PRISMA_MONO_URL}
      - YOUTUBE_KEY=${YOUTUBE_KEY}
      - SESSION_PASSWORD=${SESSION_PASSWORD}
      - NEXT_PUBLIC_MONO_API=${NEXT_PUBLIC_MONO_API}
    ports:
      - '4200:3000'

volumes:
  db-data:
