services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  minio:
    command: server --console-address ":9001" /data/
    restart: always
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: '${MINIO_ROOT_USER}'
      MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD}'
    volumes:
      - /home/sygeman/minio/data:/data
      - /data

  api:
    image: ghcr.io/sygeman/dream/mono-api
    ports:
      - '3333:3333'
    environment:
      - PRISMA_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      - REDIS_URL=redis://redis:6379
      - TWITCH_ID=${TWITCH_ID}
      - TWITCH_SECRET=${TWITCH_SECRET}
      - YOUTUBE_KEY=${YOUTUBE_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - NEXT_PUBLIC_MONO_API=${NEXT_PUBLIC_MONO_API}

  client:
    image: ghcr.io/sygeman/dream/mono-client
    environment:
      PRISMA_URL: '${PRISMA_URL}'
      YOUTUBE_KEY: '${YOUTUBE_KEY}'
      SESSION_PASSWORD: '${SESSION_PASSWORD}'
      NEXT_PUBLIC_MONO_API: '${NEXT_PUBLIC_MONO_API}'
      S3_ENDPOINT: '${S3_ENDPOINT}'
      S3_ACCESS_KEY: '${S3_ACCESS_KEY}'
      S3_SECRET_KEY: '${S3_SECRET_KEY}'
    ports:
      - '4200:3000'

volumes:
  db-data:
