services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  soketi:
    image: quay.io/soketi/soketi:latest-16-alpine
    restart: always
    ports:
      - '6001:6001'
      - '9601:9601'

  minio:
    command: server --console-address ":9001" /data/
    restart: always
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: '${MINIO_ROOT_USER}'
      MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD}'
    volumes:
      - /home/sygeman/minio/data:/data
      - /data

volumes:
  db-data:
