name: API

on: [push]

jobs:
  build_api:
    name: Build pepega-api app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('yarn.lock') }}-${{ secrets.CACHE_VERSION }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Build apps
        run: yarn build pepega-api --prod

      # Docker

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          file: apps/pepega-api/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/api:latest, ghcr.io/${{ github.repository }}/api:${{ steps.vars.outputs.sha_short }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/api:latest
          cache-to: type=inline

  deploy_api:
    name: Deploy pepega-api app
    runs-on: ubuntu-latest
    needs: build_api
    steps:
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Deploy to cluster
        uses: sekassel-research/actions-rancher-update@2.0.2
        with:
          rancher_url: https://rancher.sgmn.dev
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.CLUSTER_ID }}
          project_id: ${{ secrets.PROJECT_ID }}
          namespace: ${{ secrets.NAMESPACE }}
          deployment: ${{ secrets.DEPLOYMENT }}
          docker_image: ghcr.io/${{ github.repository }}/api:latest
